/* Generated by Yosys 0.5 (git sha1 c3c9fbf, gcc 4.8.2-19ubuntu1 -O2 -fstack-protector -fPIC -Os) */

(* top =  1  *)
(* src = "test.v:1" *)
module dffr_17(q, d, clk, reset);
  (* src = "test.v:5" *)
  input clk;
  (* src = "test.v:4" *)
  input [16:0] d;
  (* src = "test.v:3" *)
  output [16:0] q;
  (* src = "test.v:5" *)
  input reset;
  DFFSR _00_ (
    .CLK(clk),
    .D(d[0]),
    .Q(q[0]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _01_ (
    .CLK(clk),
    .D(d[1]),
    .Q(q[1]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _02_ (
    .CLK(clk),
    .D(d[2]),
    .Q(q[2]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _03_ (
    .CLK(clk),
    .D(d[3]),
    .Q(q[3]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _04_ (
    .CLK(clk),
    .D(d[4]),
    .Q(q[4]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _05_ (
    .CLK(clk),
    .D(d[5]),
    .Q(q[5]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _06_ (
    .CLK(clk),
    .D(d[6]),
    .Q(q[6]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _07_ (
    .CLK(clk),
    .D(d[7]),
    .Q(q[7]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _08_ (
    .CLK(clk),
    .D(d[8]),
    .Q(q[8]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _09_ (
    .CLK(clk),
    .D(d[9]),
    .Q(q[9]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _10_ (
    .CLK(clk),
    .D(d[10]),
    .Q(q[10]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _11_ (
    .CLK(clk),
    .D(d[11]),
    .Q(q[11]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _12_ (
    .CLK(clk),
    .D(d[12]),
    .Q(q[12]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _13_ (
    .CLK(clk),
    .D(d[13]),
    .Q(q[13]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _14_ (
    .CLK(clk),
    .D(d[14]),
    .Q(q[14]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _15_ (
    .CLK(clk),
    .D(d[15]),
    .Q(q[15]),
    .R(reset),
    .S(1'b1)
  );
  DFFSR _16_ (
    .CLK(clk),
    .D(d[16]),
    .Q(q[16]),
    .R(reset),
    .S(1'b1)
  );
endmodule
